import type { AppNotification, CommunicationLog, Member, MaritalStatus, MembershipType, Transaction, TransactionType, ChurchEvent, ChurchEventType, AuditLog, Budget, RecurringExpense, Group, MemberActivity, Sermon, Household, MemberFollowUp, MemberStatusHistory, MemberAttendanceSummary, Fund, ChurchProject, Expense, FinancialAuditLog } from '../../types';
import { MemberStatus } from '../../types';
import type { AppView } from '../../types';
import type { MemberRow, TransactionRow, ChurchEventRow, BudgetRow, RecurringExpenseRow, CommunicationRow, NotificationRow, GroupRow, ActivityRow, AuditLogRow, SermonRow, HouseholdRow, MemberFollowUpRow, MemberStatusHistoryRow, MemberAttendanceSummaryRow, FundRow, ChurchProjectRow, ExpenseRow, FinancialAuditLogRow } from './database.types';
export function mapMember(r:MemberRow):Member{return{id:r.id,firstName:r.first_name,lastName:r.last_name,phone:r.phone||'',email:r.email||'',location:r.location||'',groups:r.groups||[],status:(r.status as MemberStatus)||MemberStatus.ACTIVE,joinDate:r.join_date||'',gender:(r.gender||undefined) as Member['gender']|undefined,maritalStatus:r.marital_status as MaritalStatus||undefined,membershipType:r.membership_type as MembershipType||undefined,age:r.age||undefined,photo:r.photo||undefined,stewardshipScore:r.stewardship_score||undefined};}
export function mapTransaction(r:TransactionRow):Transaction{return{id:r.id,memberId:r.member_id||undefined,memberName:r.member_name||'',amount:r.amount,type:r.type as TransactionType,paymentMethod:r.payment_method as Transaction['paymentMethod'],date:r.date,reference:r.reference||'',category:r.category as Transaction['category'],notes:r.notes||undefined,phoneNumber:r.phone_number||undefined,source:(r.source||'MANUAL') as Transaction['source'],fundId:r.fund_id||undefined,projectId:r.project_id||undefined};}
export function mapEvent(r:ChurchEventRow):ChurchEvent{return{id:r.id,title:r.title,description:r.description||'',date:r.date,time:r.time||'',location:r.location||'',type:r.type as ChurchEventType,attendance:r.attendance||[],coordinator:r.coordinator||undefined,contactPerson:r.contact_person||undefined,rsvpDeadline:r.rsvp_deadline||undefined,recurrence:(r.recurrence||undefined) as ChurchEvent['recurrence']};}
export function mapBudget(r:BudgetRow):Budget{return{id:r.id,category:r.category,amount:r.amount,spent:r.spent||0,month:r.month};}
export function mapRecurringExpense(r:RecurringExpenseRow):RecurringExpense{return{id:r.id,category:r.category,amount:r.amount,frequency:r.frequency as RecurringExpense['frequency'],nextDate:r.next_date||''};}
export function mapCommunication(r:CommunicationRow):CommunicationLog{return{id:r.id,type:r.type as CommunicationLog['type'],recipientCount:r.recipient_count||0,targetGroupName:r.target_group_name||'',subject:r.subject||'',content:r.content,date:r.date,status:(r.status||'Sent') as CommunicationLog['status'],sender:r.sender||'',scheduledFor:r.scheduled_for||undefined,deliveryBreakdown:(r.delivery_breakdown as CommunicationLog['deliveryBreakdown'])||undefined};}
export function mapNotification(r:NotificationRow):AppNotification{return{id:r.id,title:r.title,message:r.message,time:r.time||'',type:r.type as AppNotification['type'],read:r.read||false};}
export function mapGroup(r:GroupRow):Group{return{id:r.id,name:r.name,description:r.description||'',memberCount:r.member_count||0,churchId:r.church_id,createdAt:r.created_at||'',updatedAt:r.updated_at||''};}
export function mapActivity(r:ActivityRow):MemberActivity{return{id:r.id,memberId:r.member_id||'',type:r.type as MemberActivity['type'],description:r.description||'',timestamp:r.timestamp||r.created_at||'',metadata:r.metadata};}
export function mapAuditLog(r:AuditLogRow):AuditLog{return{id:r.id,userId:r.user_id||'',userName:r.user_name||'',action:r.action,module:r.module as AppView,timestamp:r.timestamp||new Date().toISOString(),severity:(r.severity as AuditLog['severity'])||'INFO'};}
export function mapSermon(r:SermonRow):Sermon{return{id:r.id,title:r.title,speaker:r.speaker||'',date:r.date||'',time:r.time||'',scripture:r.scripture||'',event:r.event||'',eventId:r.event_id||'',transcript:r.transcript||''};}
export function mapHousehold(r:HouseholdRow):Household{return{id:r.id,churchId:r.church_id,name:r.name,address:r.address||undefined,notes:r.notes||undefined};}
export function mapFollowUp(r:MemberFollowUpRow):MemberFollowUp{return{id:r.id,churchId:r.church_id,memberId:r.member_id,type:r.type,status:r.status as MemberFollowUp['status'],dueDate:r.due_date||undefined,notes:r.notes||undefined};}
export function mapStatusHistory(r:MemberStatusHistoryRow):MemberStatusHistory{return{id:r.id,churchId:r.church_id,memberId:r.member_id,fromStatus:r.from_status||undefined,toStatus:r.to_status,reason:r.reason||undefined,changedAt:r.changed_at,changedBy:r.changed_by||undefined};}
export function mapAttendanceSummary(r:MemberAttendanceSummaryRow):MemberAttendanceSummary{return{memberId:r.member_id,attendedEvents:r.attended_events,trackedEvents:r.tracked_events,attendanceRate:Number(r.attendance_rate||0),lastAttendanceDate:r.last_attendance_date||undefined};}
export function mapFund(r:FundRow):Fund{return{id:r.id,churchId:r.church_id,name:r.name,code:r.code,description:r.description||undefined,active:r.active};}
export function mapProject(r:ChurchProjectRow):ChurchProject{return{id:r.id,churchId:r.church_id,name:r.name,accountPrefix:r.account_prefix,description:r.description||undefined,targetAmount:Number(r.target_amount||0),active:r.active,startDate:r.start_date||undefined,endDate:r.end_date||undefined};}
export function mapExpense(r:ExpenseRow):Expense{return{id:r.id,churchId:r.church_id,transactionId:r.transaction_id||undefined,category:r.category,description:r.description,amount:Number(r.amount),expenseDate:r.expense_date,vendor:r.vendor||undefined,receiptReference:r.receipt_reference||undefined,status:r.status as Expense['status'],createdBy:r.created_by||undefined};}
export function mapFinancialAuditLog(r:FinancialAuditLogRow):FinancialAuditLog{return{id:r.id,churchId:r.church_id,actorId:r.actor_id||undefined,action:r.action,entityType:r.entity_type,entityId:r.entity_id||undefined,amount:r.amount==null?undefined:Number(r.amount),metadata:(r.metadata as Record<string,unknown>)||{},createdAt:r.created_at};}
